language: r
sudo: required
cache: packages

git:
  depth: 3

r_packages:
    - rmarkdown
    - dplyr
    - testthat
    - purrr
    - checkpoint

install:
    - Rscript -e "if (!require('checkpoint')) install.packages('checkpoint', dependencies=TRUE)"
    - Rscript -e "if (!require('rmarkdown')) install.packages('rmarkdown', dependencies=TRUE)"
    - Rscript -e "if (!require('dplyr')) install.packages('dplyr', dependedncies=TRUE)"
    - Rscript -e "if (!require('purrr')) install.packages('purrr', dependencies=TRUE)"

before_script:
    - chmod +x ./_build.sh
    - chmod +x ./_deploy.sh

script:
    - ./_build.sh
    - ./_deploy.sh
